### ISSUE TITLE
RegExp support

### ISSUE THREAD

**Issue by Aurelain** [moagrius/stripcomments#2]
These 2 examples are detected as comment when in fact they're valid RegExp:

``` js
var a = /\/*x*/;
var b = /x\//;
```

Current (mistaken) output:

``` js
var a = /\;
var b = /x\
```

Fixing this needs some important changes.

**Comment by moagrius** [comment]
I'll check it out, thanks

**Comment by aemstarr** [comment]
Latest commit should address the Regex issue.
