### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by andreashuetter** [moagrius/stripcomments#4]
Two things:
1. Could you please add the information under which license (e.g. MIT) your code is released?
2. Would it be possible to release this as an npm package so it can be used in Node.js via 'require'? In case you don't have the time, would you allow someone else to fork your code in order to accomplish this?

**Comment by moagrius** [comment]
1.  Added https://github.com/moagrius/stripcomments/blob/master/LICENSE
2.  Forks are welcome.  You can maintain it yourself, or if you create it as a separate file, I'd be happy to merge after a PR and make part of this repo.
